/**
 * The signature corpus.
 *
 * Every template is a pair: a `message` (the body of the sign-off) and a
 * `signer` (how the name itself is written). Both support the placeholders
 * {name}, {title}, {company} and {recipient}; unresolved placeholders are
 * dropped by the renderer so a template never leaks braces to a caller.
 */
export interface Template {
  /** The sign-off line, e.g. "Best regards,". */
  message: string;
  /** How the name is presented, e.g. "Cap'n {name}". Defaults to "{name}". */
  signer?: string;
}

export interface Category {
  /** URL slug, e.g. "passive-aggressive". */
  slug: string;
  /** Human readable name for docs and the homepage. */
  name: string;
  /** One line description. */
  description: string;
  /** Alternate slugs that resolve to this category. */
  aliases: string[];
  templates: Template[];
}

export const CATEGORIES: Category[] = [
  {
    slug: "normal",
    name: "Normal",
    description: "Standard, polite sign-offs that will never get you in trouble.",
    aliases: ["standard", "polite"],
    templates: [
      { message: "Best regards," },
      { message: "Kind regards," },
      { message: "Thanks for your time," },
      { message: "All the best," },
      { message: "Looking forward to hearing from you," },
      { message: "Warm regards," },
      { message: "Talk soon," },
      { message: "Many thanks," },
      { message: "With appreciation," },
      { message: "Sincerely," },
      { message: "Yours truly," },
      { message: "Thanks again for your help," },
      { message: "Have a good week," },
      { message: "Appreciate you taking a look," },
      { message: "Let me know what you think," },
      { message: "Speak soon," },
      { message: "Cheers," },
    ],
  },
  {
    slug: "business",
    name: "Business",
    description: "Corporate and highly professional. Pairs well with ?title= and ?company=.",
    aliases: ["corporate", "professional", "formal"],
    templates: [
      { message: "Respectfully yours," },
      { message: "Yours in synergy," },
      { message: "Please let me know how you would like to proceed," },
      { message: "Happy to take this offline if that is easier," },
      { message: "Thank you for the partnership," },
      { message: "At your convenience," },
      { message: "Circling back with next steps shortly," },
      { message: "Flagging this for your awareness," },
      { message: "Ready to move when you are," },
      { message: "Aligning on scope before we proceed," },
      { message: "Grateful for the continued partnership," },
      { message: "Open to feedback on the approach," },
      { message: "Sharing this ahead of the review," },
      { message: "Following up with a summary by end of day," },
      { message: "Confident this gets us to the outcome," },
      { message: "Thank you for the visibility," },
      { message: "Looping back once we have alignment," },
    ],
  },
  {
    slug: "funny",
    name: "Funny",
    description: "Humorous and lighthearted.",
    aliases: ["humor", "humour", "jokes"],
    templates: [
      { message: "Stay out of trouble. Or don't." },
      { message: "Sent from my phone, so blame the typos on physics." },
      { message: "I have run out of email and must go now." },
      { message: "May your coffee be strong and your meetings be cancelled." },
      { message: "This message was written by a professional. Do not attempt." },
      { message: "Anyway, that's enough words for one day." },
      { message: "Yours, until the next reply-all incident," },
      { message: "I am contractually obliged to stop typing now." },
      { message: "This email took eleven minutes and two drafts." },
      { message: "Signing off before I say something quotable." },
      { message: "Written with confidence, sent with hope." },
      { message: "Please imagine a firm handshake here." },
      { message: "That is the entire thought. There is no more thought." },
      { message: "Consider this the director's cut of a much shorter idea." },
      { message: "Sent at a speed that suggests urgency I do not feel." },
      { message: "Wishing you fewer notifications than I have." },
      { message: "Yours, before the meeting that could have been this email," },
      { message: "Emailing from a chair I should have replaced years ago," },
    ],
  },
  {
    slug: "mad",
    name: "Mad",
    description: "Aggressive, fed up, and completely out of patience.",
    aliases: ["angry", "furious", "annoyed"],
    templates: [
      { message: "Do not reply to this." },
      { message: "I am done discussing this." },
      { message: "Figure it out." },
      { message: "This is the last time I explain this." },
      { message: "Consider this matter closed." },
      { message: "Lose my address." },
      { message: "Absolutely not," },
      { message: "We are not doing this again." },
      { message: "The answer was no the first three times." },
      { message: "I have nothing further." },
      { message: "Read the thread." },
      { message: "This was avoidable." },
      { message: "Do not loop me back in." },
      { message: "I will not be revisiting this." },
      { message: "Handle it." },
      { message: "Take this off my calendar." },
      { message: "Enough." },
    ],
  },
  {
    slug: "passive-aggressive",
    name: "Passive-Aggressive",
    description: "Subtly hostile corporate speak. Deniable, but only barely.",
    aliases: ["passiveaggressive", "pa"],
    templates: [
      { message: "Per my last email," },
      { message: "I trust you can figure it out from here." },
      { message: "Just circling back on this, again." },
      { message: "As previously discussed (twice)," },
      { message: "Happy to walk you through it a third time," },
      { message: "Adding some people to this thread for visibility." },
      { message: "Let me know if anything about this is still unclear." },
      { message: "Reattaching the document that was already attached." },
      { message: "Bumping this to the top of your inbox, in case it sank." },
      { message: "No rush, unless it was due Monday." },
      { message: "Attaching it again, in a different file format this time." },
      { message: "Sorry, I assumed the deadline was shared knowledge." },
      { message: "Copying your manager purely for context." },
      { message: "Resending in case the first two went to spam." },
      { message: "Marking this urgent so it stands out among the others." },
      { message: "Thanks in advance for the reply I am sure is coming." },
      { message: "Correcting the record for anyone joining late," },
      { message: "Glad we could align, eventually," },
    ],
  },
  {
    slug: "overly-enthusiastic",
    name: "Overly Enthusiastic",
    description: "Way too much energy for an email.",
    aliases: ["enthusiastic", "hype", "excited"],
    templates: [
      { message: "STAY AWESOME AND CRUSH IT!!! \u{1F680}\u{1F525}" },
      { message: "SO PUMPED FOR THIS!!! LET'S GOOOO!!! \u{1F389}" },
      { message: "BEST EMAIL OF MY ENTIRE LIFE!!! THANK YOU!!!" },
      { message: "ONWARD AND UPWARD, LEGEND!!! \u{2B06}\u{FE0F}\u{2728}" },
      { message: "YOU ARE ABSOLUTELY SMASHING IT!!! \u{1F4AA}" },
      { message: "CANNOT WAIT TO DO THIS AGAIN!!! \u{1F31F}" },
      { message: "HAVE THE MOST INCREDIBLE DAY EVER!!!" },
      { message: "THIS IS THE BEST THREAD I HAVE EVER BEEN ON!!!" },
      { message: "OBSESSED WITH THIS ENERGY!!! KEEP GOING!!! \u{1F929}" },
      { message: "GENUINELY HONOURED TO BE CC'D ON THIS!!!" },
      { message: "SENDING MAXIMUM GOOD VIBES YOUR WAY!!! \u{2600}\u{FE0F}" },
      { message: "LET'S ABSOLUTELY DEMOLISH THIS TOGETHER!!! \u{1F4A5}" },
      { message: "I READ THIS TWICE BECAUSE IT WAS THAT GOOD!!!" },
      { message: "FIRED UP AND IT IS NOT EVEN TUESDAY YET!!! \u{1F525}" },
      { message: "THANK YOU THANK YOU THANK YOU!!! \u{1F64C}" },
      { message: "EVERY EMAIL WITH YOU IS A HIGHLIGHT!!! \u{2728}" },
      { message: "GO BE MAGNIFICENT TODAY!!! \u{1F31E}" },
    ],
  },
  {
    slug: "gen-z",
    name: "Gen-Z",
    description: "Heavy use of modern internet slang.",
    aliases: ["genz", "zoomer"],
    templates: [
      { message: "No cap, this email is over." },
      { message: "Ok that's the whole vibe, bye." },
      { message: "Lowkey done typing now." },
      { message: "It's giving end of message." },
      { message: "Anyway, slay." },
      { message: "Bet. Talk later." },
      { message: "That's so real of you, ttyl." },
      { message: "Ok I said what I said, bye." },
      { message: "Respectfully, that's the whole update." },
      { message: "Not me writing a whole essay, anyway." },
      { message: "Delulu but hopeful, talk soon." },
      { message: "Sending this and touching grass." },
      { message: "Idk, thoughts? No pressure fr." },
      { message: "That's the tea, catch you later." },
      { message: "Periodt. End of email." },
      { message: "We move. Bye for now." },
      { message: "This email is so mid, sorry." },
    ],
  },
  {
    slug: "cryptic",
    name: "Cryptic",
    description: "Mysterious, ominous, and deeply unhelpful.",
    aliases: ["mysterious", "vague"],
    templates: [
      { message: "The owl flies at midnight." },
      { message: "Burn this after reading." },
      { message: "You already know what to do." },
      { message: "The package is where we agreed." },
      { message: "Say nothing to the others." },
      { message: "Three knocks. Never four." },
      { message: "We were never here." },
      { message: "The second envelope is the real one." },
      { message: "If I do not write again, you will know why." },
      { message: "Ask about the garden. Never about the gate." },
      { message: "The numbers were never the point." },
      { message: "Do not use this address after Thursday." },
      { message: "The others believe the meeting was cancelled." },
      { message: "You will know the courier by the missing button." },
      { message: "Everything you need is in the third paragraph." },
      { message: "Delete nothing. Trust less." },
      { message: "Wait for the second bell." },
    ],
  },
  {
    slug: "shakespearean",
    name: "Shakespearean",
    description: "Old English, poetic flair, an unreasonable number of thees.",
    aliases: ["shakespeare", "bard", "olde"],
    templates: [
      { message: "I bid thee farewell,", signer: "thy humble servant, {name}" },
      { message: "Parting is such sweet sorrow,", signer: "thine ever, {name}" },
      { message: "Fare thee well, and prosper,", signer: "thy loyal {name}" },
      { message: "Anon, good friend, anon.", signer: "thy servant, {name}" },
      { message: "Thus concludes this humble missive,", signer: "{name}, of the quill" },
      { message: "Get thee to thine inbox,", signer: "thy wretched correspondent, {name}" },
      { message: "Adieu, and let no reply be tardy,", signer: "thy patient {name}" },
      { message: "Herein ends my discourse, good soul,", signer: "{name}, humble scribe" },
      { message: "The rest is silence, and also the attachment,", signer: "thy {name}" },
      { message: "Pray, look kindly upon this missive,", signer: "thine own {name}" },
      { message: "Till we meet again in some fairer inbox,", signer: "thy devoted {name}" },
      { message: "Good morrow, and may thy calendar be light,", signer: "thy servant {name}" },
      { message: "What is writ is writ, and cannot be unsent,", signer: "{name}, of the quill" },
      { message: "I take my leave, ere I grow tedious,", signer: "thy weary {name}" },
      {
        message: "Lend me thine eyes but once more,",
        signer: "thy suitor in correspondence, {name}",
      },
      { message: "By my troth, the matter is now thine,", signer: "thy {name}" },
      { message: "Exeunt, pursued by a deadline,", signer: "{name}, lately of the stage" },
    ],
  },
  {
    slug: "existential-dread",
    name: "Existential Dread",
    description: "Nihilistic, bleak, and technically still a valid sign-off.",
    aliases: ["existential", "dread", "nihilist", "nihilism"],
    templates: [
      { message: "Nothing matters anyway." },
      { message: "We will all be forgotten, but here is the attachment." },
      { message: "The heat death of the universe is also on the roadmap." },
      { message: "Reply, don't reply. The void is patient." },
      { message: "Another email, another second closer to the end." },
      { message: "Nothing we ship will outlive the sun." },
      { message: "Sent into the indifferent dark," },
      { message: "Time is a flat inbox." },
      { message: "Your reply and its absence weigh the same." },
      { message: "We are dust that learned to schedule things." },
      { message: "The thread continues. We do not." },
      { message: "Somewhere a server will remember this longer than we will." },
      { message: "There is no deadline the universe respects." },
      { message: "I wrote this so that something would exist." },
      { message: "The meeting will end. So will everything." },
      { message: "Everything ships, eventually, into nothing." },
      { message: "Regards, for whatever regard is worth," },
      { message: "Sent while briefly conscious," },
    ],
  },
  {
    slug: "sci-fi",
    name: "Sci-Fi / Robot",
    description: "Automated, futuristic, faintly threatening sign-offs.",
    aliases: ["scifi", "robot", "android"],
    templates: [
      { message: "End of transmission. Unit {name} powering down.", signer: "UNIT {name}" },
      { message: "Message compiled successfully. Terminating link.", signer: "UNIT {name}" },
      { message: "Awaiting further instruction, carbon-based lifeform.", signer: "UNIT {name}" },
      { message: "Signal degrading. Retransmit if unread.", signer: "UNIT {name}" },
      { message: "This unit has fulfilled its communication quota.", signer: "UNIT {name}" },
      { message: "Sent across four light-years and one firewall.", signer: "UNIT {name}" },
      { message: "Handshake complete. Closing channel.", signer: "UNIT {name}" },
      { message: "Directive fulfilled. Returning to standby.", signer: "UNIT {name}" },
      { message: "Your response window opens in three cycles.", signer: "UNIT {name}" },
      { message: "This message survived the ionosphere. Be gentle with it.", signer: "UNIT {name}" },
      { message: "Memory purge scheduled. Reply before it runs.", signer: "UNIT {name}" },
      { message: "Organic sentiment detected. Logging it anyway.", signer: "UNIT {name}" },
      { message: "Coordinates attached. Do not deviate.", signer: "UNIT {name}" },
      { message: "Transmission ends. Long live the mesh.", signer: "UNIT {name}" },
      { message: "Rebooting empathy subroutine after send.", signer: "UNIT {name}" },
      { message: "Ninety-nine percent certainty this reaches you.", signer: "UNIT {name}" },
      { message: "Powering down until further input.", signer: "UNIT {name}" },
    ],
  },
  {
    slug: "apocalyptic",
    name: "Apocalyptic",
    description: "Survivalist tone for the post-inbox world.",
    aliases: ["apocalypse", "wasteland", "doomsday"],
    templates: [
      { message: "Stay safe in the wasteland." },
      { message: "Ration your replies. There are not many left." },
      { message: "Trade in canned goods, not calendar invites." },
      { message: "If the radio goes quiet, keep heading north." },
      { message: "Boil the water. Trust no one. Reply by dusk." },
      { message: "Keep your inbox loaded and your door barred." },
      { message: "See you on the other side of it,", signer: "Survivor {name}" },
      { message: "The convoy leaves at first light, with or without your reply." },
      { message: "Bring batteries. Bring the letter." },
      { message: "The relay towers are down past the ridge." },
      { message: "Do not open the door for anyone quoting policy." },
      { message: "We buried the servers. They were heavy." },
      { message: "Save the last of the coffee for the long night." },
      { message: "Count the days. Ration the hope." },
      { message: "Burn the calendar. It is not helping." },
      { message: "If this reaches you, the relay still works,", signer: "Survivor {name}" },
      { message: "Head for the water, and do not look back,", signer: "Survivor {name}" },
    ],
  },
  {
    slug: "pirate",
    name: "Pirate",
    description: "Swashbuckling sign-offs for the seven seas.",
    aliases: ["pirates", "arr", "buccaneer"],
    templates: [
      { message: "Fair winds and following seas,", signer: "Cap'n {name}" },
      { message: "May yer anchor be tight and yer compass true.", signer: "Cap'n {name}" },
      { message: "Reply swift, or walk the plank.", signer: "Cap'n {name}" },
      { message: "Yo ho, and mind the kraken.", signer: "Cap'n {name}" },
      { message: "The treasure be in the attachment, savvy?", signer: "Cap'n {name}" },
      { message: "Dead men send no follow-ups.", signer: "Cap'n {name}" },
      { message: "Arrr, that be all for now.", signer: "Cap'n {name}" },
      { message: "Set yer sails, the tide waits fer no inbox.", signer: "Cap'n {name}" },
      { message: "There be no CC on the high seas.", signer: "Cap'n {name}" },
      { message: "Mind the reef, and mind yer tone.", signer: "Cap'n {name}" },
      { message: "Ye owe me a reply and a barrel o' rum.", signer: "Cap'n {name}" },
      { message: "Sixteen men, one attachment.", signer: "Cap'n {name}" },
      { message: "I marked the spot. Ye lost the map.", signer: "Cap'n {name}" },
      { message: "Storm's comin'. Answer quick.", signer: "Cap'n {name}" },
      { message: "No quarter, and no follow-ups.", signer: "Cap'n {name}" },
      { message: "Aye, that be the whole of it.", signer: "Cap'n {name}" },
      { message: "Weigh anchor and write back,", signer: "Cap'n {name}" },
    ],
  },
  {
    slug: "needy",
    name: "Needy",
    description: "Desperate for a response. Any response.",
    aliases: ["clingy", "desperate"],
    templates: [
      { message: "Please write back soon, I'm waiting here..." },
      { message: "Did I say something wrong? It's fine either way. Is it?" },
      { message: "You don't have to reply. But it would mean a lot." },
      { message: "Still refreshing my inbox. No pressure." },
      { message: "I'll just be here. Waiting. Whenever you're ready." },
      { message: "Even a one-word reply would honestly make my week." },
      { message: "Sorry for the follow-up. And for this follow-up." },
      { message: "I reread my last email. It was fine, right?" },
      { message: "Just checking that the email actually sent. It did." },
      { message: "Not urgent. Not not urgent." },
      { message: "I'll take a thumbs up. I'll take anything." },
      { message: "Hope you're okay. That's mostly why I wrote." },
      { message: "Is this a bad time? It's fine if it is." },
      { message: "You're probably busy. I've decided that's why." },
      { message: "I moved my chair so I can see the notification." },
      { message: "One more email and then I'll stop. Probably." },
      { message: "Talk soon? Please?" },
    ],
  },
  {
    slug: "noir",
    name: "Noir",
    description: "Hardboiled, rain-slicked, and one drink past regret.",
    aliases: ["detective", "gumshoe", "hardboiled"],
    templates: [
      { message: "The rain kept coming. So did the emails." },
      { message: "I've seen cleaner threads in a dumpster." },
      { message: "She said it was urgent. They always say that." },
      { message: "Some inboxes you walk into. Some walk into you." },
      { message: "I lit a cigarette and hit send." },
      { message: "The attachment was a lie, but it was a good one." },
      { message: "In this city, everybody's got a follow-up." },
      { message: "I knew how it ended before I read the subject line." },
      { message: "Nobody sends a calendar invite for good news." },
      { message: "The office was quiet. Nobody replies at three in the morning." },
      { message: "You want the truth? It's in the last paragraph." },
      { message: "I've been paid to forget worse threads than this one." },
      { message: "Trouble came in wearing a read receipt." },
      { message: "There are eight million emails in the naked city. This was one." },
      { message: "Keep your door locked and your drafts folder empty." },
      { message: "It was the kind of ask that never comes back clean." },
      { message: "I filed it under things I'd regret,", signer: "{name}, private correspondence" },
      { message: "Yours, until the case closes,", signer: "{name}, private correspondence" },
    ],
  },
  {
    slug: "cowboy",
    name: "Cowboy",
    description: "Dust, distance, and not many words.",
    aliases: ["western", "wildwest", "yeehaw"],
    templates: [
      { message: "Much obliged." },
      { message: "Ride safe." },
      { message: "That's all the daylight I've got." },
      { message: "Reckon that about covers it." },
      { message: "See you at the crossing." },
      { message: "Keep your powder dry and your inbox lighter." },
      { message: "No use burning good horse over a small matter." },
      { message: "I said my piece." },
      { message: "Sun's going down. So am I." },
      { message: "Obliged for the trouble you took." },
      { message: "Ain't nothing out here but us and the reply-alls." },
      { message: "Meet me where the road bends." },
      { message: "Water the horse before you answer." },
      { message: "A man's word and a sent folder are all he's got." },
      { message: "Long ride ahead. Short letter." },
      { message: "Happy trails," },
      { message: "Yours across the territory," },
      { message: "Til the next town," },
    ],
  },
  {
    slug: "legalese",
    name: "Legalese",
    description: "Contract voice. Nothing admitted, nothing denied.",
    aliases: ["legal", "lawyer", "contract"],
    templates: [
      { message: "Without prejudice to the foregoing," },
      { message: "Please be advised that this email speaks for itself." },
      { message: "Nothing herein constitutes agreement, comfort or advice." },
      { message: "Reserving all rights, including the right to send this again." },
      { message: "The undersigned considers the matter addressed." },
      { message: "Time is of the essence, as it has been since Tuesday." },
      { message: "Kindly govern yourself accordingly." },
      { message: "This correspondence supersedes all prior correspondence." },
      { message: "Notwithstanding anything to the contrary in your last message," },
      { message: "Attached herewith, and incorporated by reference," },
      { message: "A response is requested within a commercially reasonable period." },
      { message: "Silence shall not be construed as consent." },
      { message: "The parties are encouraged to resolve this informally." },
      { message: "Please direct further correspondence to this address." },
      { message: "Consider this notice duly served." },
      { message: "Yours faithfully, and subject to contract," },
      {
        message: "Executed and sent this day, electronically,",
        signer: "{name}, for and on behalf of the undersigned",
      },
      { message: "Respectfully submitted,", signer: "{name}, counsel of record" },
    ],
  },
  {
    slug: "academic",
    name: "Academic",
    description: "Peer-reviewed sign-offs with a footnote's worth of hedging.",
    aliases: ["scholar", "peer-review", "thesis"],
    templates: [
      { message: "Further work is required, as ever." },
      { message: "This finding is preliminary and should be treated as such." },
      { message: "I defer to the literature, and to you." },
      { message: "Happy to discuss at greater length than anyone wants." },
      { message: "The limitations of this email are discussed below." },
      { message: "With apologies for the length and for the citations," },
      { message: "The data are, at best, suggestive." },
      { message: "I look forward to your comments, however brutal." },
      { message: "Reviewer 2 would have hated this email." },
      { message: "More study is needed. There always is." },
      { message: "The argument holds, provided you accept the premise." },
      { message: "As I argued at length elsewhere," },
      { message: "This remains an open question," },
      { message: "Corrections gratefully received," },
      { message: "Pending revisions," },
      { message: "In collegial regard," },
      { message: "Submitted for your consideration,", signer: "{name}" },
      { message: "With scholarly regards,", signer: "{name}" },
    ],
  },
  {
    slug: "founder",
    name: "Startup Founder",
    description: "Fundraising cadence and permanent momentum.",
    aliases: ["startup", "vc", "hustle"],
    templates: [
      { message: "Huge if true. Building anyway." },
      { message: "Shipping tonight, sleeping in Q4." },
      { message: "Let's find thirty minutes and change the category." },
      { message: "We are early, which is the whole point." },
      { message: "Momentum compounds. So do replies." },
      { message: "Default alive, barely," },
      { message: "Happy to send the deck. It is short." },
      { message: "Zero to one, then one to a follow-up." },
      { message: "The market will tell us. It usually does." },
      { message: "Strong signal here. Let's go deeper." },
      { message: "Building in public, replying in private," },
      { message: "We are hiring, in case this email was a pitch." },
      { message: "Talk soon. We move fast here." },
      { message: "Grateful for the intro," },
      { message: "Iterating, always," },
      { message: "Excited to keep you posted," },
      { message: "Onward," },
    ],
  },
  {
    slug: "zen",
    name: "Zen",
    description: "Calm to the point of unhelpfulness.",
    aliases: ["calm", "mindful", "meditation"],
    templates: [
      { message: "The inbox empties itself, in time." },
      { message: "Answer, or do not. Both are answers." },
      { message: "Breathe before you reply." },
      { message: "The message is not the meaning." },
      { message: "There is no urgent. There is only now." },
      { message: "Let the thread rest." },
      { message: "What is unread is not lost." },
      { message: "The reply will arrive when it arrives." },
      { message: "Empty inbox, empty mind. The same thing." },
      { message: "Do less. Send less." },
      { message: "Be where your cursor is." },
      { message: "This too will be archived." },
      { message: "Nothing to add. Everything is here." },
      { message: "Sit with it," },
      { message: "In stillness," },
      { message: "With an open hand," },
      { message: "May your notifications be few," },
    ],
  },
  {
    slug: "haiku",
    name: "Haiku",
    description: "Five syllables, seven, five. No exceptions.",
    aliases: ["poem", "poetry", "5-7-5"],
    templates: [
      { message: "The inbox is full / but the cursor keeps blinking / patient as a stone" },
      { message: "Autumn light, and still / three unanswered messages / wait beneath the fold" },
      { message: "A meeting was moved / the calendar does not care / neither does the moon" },
      { message: "Send button pressed once / the words are no longer mine / snow on the server" },
      { message: "Rain on the window / I reply to everyone / except to myself" },
      { message: "Quiet Monday mail / a thread that will not resolve / the kettle boiling" },
      { message: "One draft, then a pause / the cursor learns to be still / send it anyway" },
      { message: "Deadline like thunder / far off, then very close, then / only the echo" },
      {
        message: "The server room hums / somewhere a message waits, cold / spring will come for it",
      },
      { message: "No reply needed / the pond keeps the stone's secret / go well, and go now" },
      { message: "Two hundred unread / a heron stands in the reeds / neither of us moves" },
      { message: "This email is done / a leaf lets go of the branch / the afternoon holds" },
      {
        message: "Old thread, new subject / the same question, wearing shoes / walk it out with me",
      },
      {
        message: "Cold coffee, warm screen / the day writes itself in drafts / none of them are sent",
      },
      { message: "Attachment attached / a small boat leaves the harbour / may it find the shore" },
      {
        message: "The wind through the wires / your name at the end of it / that is the whole note",
      },
      { message: "Signing off softly / the way a door closes when / the house is asleep" },
    ],
  },
  {
    slug: "coach",
    name: "Coach",
    description: "Locker-room voice, whistle included.",
    aliases: ["sports", "locker-room", "pep-talk"],
    templates: [
      { message: "Leave it all on the field." },
      { message: "One play at a time." },
      { message: "We win Tuesdays. That's the whole strategy." },
      { message: "Nobody remembers the warm-up." },
      { message: "Get me one more rep on this." },
      { message: "You're better than this thread." },
      { message: "Film session tomorrow. Bring notes." },
      { message: "Effort is the only thing I can't coach." },
      { message: "Run it back." },
      { message: "Heads up, chests out." },
      { message: "The scoreboard doesn't read excuses." },
      { message: "Do your job." },
      { message: "Trust the reps you put in." },
      { message: "We're not tired. We're just getting started." },
      { message: "Hydrate and reply." },
      { message: "Proud of the work. Now finish it." },
      { message: "See you at practice," },
    ],
  },
  {
    slug: "conspiracy",
    name: "Conspiracy",
    description: "Everything is connected, especially the calendar.",
    aliases: ["tinfoil", "truther", "cover-up"],
    templates: [
      { message: "Ask yourself who benefits from this meeting." },
      { message: "The org chart is a distraction. Follow the budget." },
      { message: "They renamed the project for a reason." },
      { message: "Do not trust anything scheduled for a Friday." },
      { message: "I have screenshots. I always have screenshots." },
      { message: "The document was edited nine minutes before you saw it." },
      { message: "Notice how nobody replied to the first thread." },
      { message: "Coincidence is just a plan you were not shown." },
      { message: "Print this. Servers forget on purpose." },
      { message: "There is no such thing as a routine sync." },
      { message: "Wake up and read the changelog." },
      { message: "They will say I overreacted. They always do." },
      { message: "Two people knew. Now three." },
      { message: "Keep this off the shared drive." },
      { message: "Follow the calendar invites. They lead somewhere." },
      { message: "Stay alert," },
      { message: "Trust no thread," },
    ],
  },
  {
    slug: "victorian",
    name: "Victorian",
    description: "Nineteenth-century correspondence, unnecessarily obliged.",
    aliases: ["regency", "edwardian", "obedient-servant"],
    templates: [
      { message: "I trust this finds you in tolerable health." },
      { message: "Forgive the liberty of this correspondence." },
      { message: "I have the honour to be, most sincerely," },
      { message: "Pray convey my regards to the household." },
      { message: "It would gratify me exceedingly to hear from you." },
      { message: "I am, as ever, at your disposal." },
      { message: "Let us not speak of the postage." },
      { message: "With the very warmest esteem," },
      { message: "I shall await your favour by the next post." },
      { message: "Believe me, I remain entirely yours," },
      { message: "Should the weather permit, I shall call on Thursday." },
      { message: "I beg you will excuse the brevity of this note." },
      { message: "It is a small matter, and yet I could not rest." },
      { message: "I dare not presume further upon your patience." },
      { message: "Written in haste, and with great feeling," },
      { message: "Yours in the deepest respect," },
      { message: "I remain, sir or madam, your most obedient servant,", signer: "{name}" },
      { message: "Your humble correspondent,", signer: "{name}, Esq." },
    ],
  },
  {
    slug: "bureaucratic",
    name: "Bureaucratic",
    description: "Forms, reference numbers, and an office that closes at four.",
    aliases: ["red-tape", "admin", "paperwork"],
    templates: [
      { message: "Please retain this message for your records." },
      { message: "Your request has been received and placed in a queue." },
      { message: "This matter falls outside the scope of this department." },
      { message: "Kindly resubmit using the correct form." },
      { message: "A decision is expected within eight to twelve weeks." },
      { message: "The office is closed for processing until further notice." },
      { message: "Reference this thread in all future correspondence." },
      { message: "Approval is pending approval." },
      { message: "Your position in the queue has not changed." },
      { message: "This response does not constitute a response." },
      { message: "Please do not reply to this address." },
      { message: "Escalation requires a separate form." },
      { message: "Duly noted and filed," },
      { message: "Processed in the order received," },
      { message: "Stamped, dated, and forwarded," },
      { message: "Yours administratively," },
      { message: "Signed on behalf of the department,", signer: "{name}, Processing" },
    ],
  },
  {
    slug: "infomercial",
    name: "Infomercial",
    description: "But wait. There is, in fact, more.",
    aliases: ["salesman", "as-seen-on-tv", "pitch"],
    templates: [
      { message: "But wait, there's more." },
      { message: "Act now and I'll throw in a second paragraph, free." },
      { message: "Operators are standing by. It's just me. I'm the operator." },
      { message: "Tired of emails that end? This one barely does." },
      { message: "Not sold in stores. Sold in threads." },
      { message: "Call in the next ten minutes and I'll reply twice." },
      { message: "Results not typical. Neither is this email." },
      { message: "How much would you pay for this update? Don't answer yet." },
      { message: "It slices. It dices. It copies your manager." },
      { message: "Order now and receive absolutely nothing extra." },
      { message: "Satisfaction guaranteed, or your attention back." },
      { message: "That's right, folks, all in one message." },
      { message: "Supplies are limited. Patience more so." },
      { message: "You won't believe what's in the attachment." },
      { message: "Try it risk-free for thirty days," },
      { message: "Back to you, and don't forget to reply," },
      { message: "Yours, exclusively," },
    ],
  },
  {
    slug: "villain",
    name: "Villain",
    description: "Theatrically evil, impeccably polite about it.",
    aliases: ["evil", "supervillain", "nemesis"],
    templates: [
      { message: "You have until the end of the quarter." },
      { message: "How predictable of you to reply so quickly." },
      { message: "The plan proceeds. Your input was never required." },
      { message: "Do give my regards to the board." },
      { message: "I have already accounted for your objection." },
      { message: "Everything is going exactly as arranged." },
      { message: "You will understand in time. Probably too late." },
      { message: "Consider this your only warning, and a courteous one." },
      { message: "I would explain, but where would be the pleasure in that?" },
      { message: "Your calendar is mine now." },
      { message: "Fool me once. There will not be a second time." },
      { message: "I look forward to your inevitable capitulation." },
      { message: "Enjoy the weekend. It is the last one like it." },
      { message: "Yours, inevitably," },
      { message: "With sinister regards," },
      { message: "Until we meet again, unfortunately for you," },
      { message: "Farewell, and do lock the door," },
    ],
  },
  {
    slug: "tired",
    name: "Tired",
    description: "Running on fumes and two hours of sleep.",
    aliases: ["exhausted", "burnout", "sleepy"],
    templates: [
      { message: "That's everything I have in me today." },
      { message: "Sending this before I lose the thread entirely." },
      { message: "Long week. It's Tuesday." },
      { message: "I'll make sense of this in the morning." },
      { message: "My brain clocked out an hour ago." },
      { message: "Half of this email is autopilot. The good half." },
      { message: "Going to look at a wall for a while." },
      { message: "No more decisions today." },
      { message: "I read it. I promise I read it." },
      { message: "Whatever you think is best. Genuinely." },
      { message: "One more email and then the couch." },
      { message: "Please treat any typos as evidence." },
      { message: "I'll be sharper tomorrow. Probably." },
      { message: "Signing off before I fall asleep mid-sen" },
      { message: "Answering with whatever is left," },
      { message: "Running on fumes and goodwill," },
      { message: "Tired but grateful," },
      { message: "Good night, and good luck to us both," },
    ],
  },
];

const INDEX = new Map<string, Category>();
for (const category of CATEGORIES) {
  INDEX.set(category.slug, category);
  for (const alias of category.aliases) INDEX.set(alias, category);
}

/** Normalizes a user supplied slug: lowercase, underscores/spaces to dashes. */
export function normalizeSlug(input: string): string {
  return input.trim().toLowerCase().replace(/[\s_]+/g, "-");
}

export function findCategory(slug: string): Category | undefined {
  return INDEX.get(normalizeSlug(slug));
}
